# Generated by Django 4.2.20 on 2025-05-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestselleraccolade',
            name='category',
            field=models.CharField(choices=[('Top 5', 'Top 5'), ('Top 10', 'Top 10'), ('Top 25', 'Top 25')], max_length=50),
        ),
    ]
